### ISSUE TITLE
getting error with ctl_slide function definition

### ISSUE THREAD

**Issue by rbnpi** [ethancrawford/live-coding#1]
Hi Ethan
I tried your code and it gives an error when I run part 1 in the ctl_slide function defintion in line 45
which is the line control ctl_focus, {"#{slide[:param]}_slide": val[:dur]}

says Syntax error unexpected ':', expection =>
Not quite got my head round your expressions yet!
Running latest 2.6dev commit d04794e92c1db003c4d417145213b8d2ed602430 1 parent e1ae4f5

**Comment by ethancrawford** [comment]
Hmm, sorry about that! I am beginning to wonder if those support/utility functions are too complex for their own good haha. Perhaps my code needs to be more robust. Had you edited anything in my code before running it?

**Comment by rbnpi** [comment]
Don't think so. I'll try a fresh download to be sure.... put fresh copy of raw file in SP and still get the error.

**Comment by ethancrawford** [comment]
One other thing I thought of: the way I create the hash on that line might be causing it, ie if it's encountering the ':' but expecting a '=>'. Maybe there's a difference between the ruby versions we have that's causing it or something, no idea. Try changing those two lines to:
        control ctl_focus, {:"#{slide[:param]}_slide" => val[:dur]}
        control ctl_focus, {:"#{slide[:param]}" => val[:end_value]}
maybe that'll work?

**Comment by ethancrawford** [comment]
@rbnpi - when you're ready, let me know if you have any luck with replacing the two lines as mentioned above - hopefully the alternative hash syntax is successful for you.

**Comment by rbnpi** [comment]
Hi Ethan

**Comment by rbnpi** [comment]
Sorry about previous comment. using iPhone and hit wrong key! I'm on holiday and haven't got my Mac but brought a pi sarong! Tried the line changes and that sorts the error ok. However pice stops quickly with timing errors. Haven't had time to look at that yet. 
Robin

**Comment by rbnpi** [comment]
Pi along with me : not sarong :-)

**Comment by ethancrawford** [comment]
I imagined there was a good reason for your delay. No worries. I'll have to dig out my Raspberry Pi and see if there's any improvements I can make to remove the timing errors without changing the composition too much.
Enjoy the rest of your holiday :-)

**Comment by ethancrawford** [comment]
Hash syntax error fixed in e398208
